print("My name is Hema Teja Reddy")
print("==========================")
print("Studying in B.Tech final year")
print("==========================")
print("branch is Computer Science Engineering")
print("==========================")
print("college is GIET engineering college")
print("==========================")
print("my college id is 22T91A0566")
